focus-trap/focus-trap

- index.js
> Don't attempt to call 'blur' on 'document' (fixes #15)

- index.d.ts
- package.json
Added per instructions on TS [declaration files](https://www.typescriptlang.org/docs/handbook/declaration-files/by-example.html).
> Add TypeScript type declarations

- .gitignore
- package.json
- yarn.lock
Implementing browserify based build system for producing (minified)
umd builds suitable for unpkg.com. (resolves #35)
> Publish umd and minified umd versions of package

- CHANGELOG.md
- index.js
- package-lock.json
- package.json
Fixes #76 and also updates to the newest faster tabbable.
> Optimize the usage of tabbable

- index.js
Fixes https://github.com/davidtheclark/focus-trap/issues/81
> Clear delay before autofocus in deactivate method

- index.d.ts
Related: https://github.com/davidtheclark/focus-trap/issues/104
> ts: Add typedef for `preventScroll` option

- cypress/integration/focus-trap-demo.spec.js
- demo/index.html
Refer back to #143 Add some cypress tests against current demo pages. 
👉 If any of these don't apply, please ~cross them out~.
> Some cypress tests

- cypress/integration/focus-trap-demo.spec.js
- demo/index.html
Refer back to #143 Add some cypress tests against current demo pages.
> More cypress tests

- .eslintrc.json
- cypress/integration/focus-trap-demo.spec.js
- package.json
- yarn.lock
Refer back to #143 
1. Complete all cypress tests(except for one possible defect) against current demo pages. 
1. Extract common focus free-from-trap verify function for almost each test cases.
> All cypress tests

- .changeset/sweet-wombats-jam.md
- README.md
- demo/js/allow-outside-click.js
- demo/js/default.js
- demo/js/delay.js
- demo/js/hidden-treasures.js
- demo/js/iframe.js
- demo/js/initial-element-no-escape.js
- demo/js/initially-focused-container.js
- demo/js/input-activation.js
- demo/js/multiple-elements.js
- demo/js/multiple-traps-multiple-elements.js
- demo/js/nested.js
- demo/js/no-delay.js
- demo/js/radio.js
- demo/js/set-return-focus.js
- demo/js/sibling.js
- demo/js/tricky-initial-focus.js
- index.js
Since I was in here, I thought I would put up a simple PR that had no functionality change.  These changes are just about changing vars to let/const (no more vars in repo), simplifying a few lines, etc.
Not offended if these are not desirable.
> Refactoring to use const/let, and simplify a few lines

- docs/index.html
- docs/js/animated-trigger.js
Made some suggestions for `index.html` and made some small code tweaks
<details>
<br/>
- Includes updated `/docs/demo-bundle.js` if source or docs code was changed.
- EXCEPTION: A Changeset is not required if the change does not affect any of the source files that produce the package bundle. For example, tooling changes, test updates, or a new dev-only …
> Postdeactivate PR suggestions

- .changeset/smooth-rats-poke.md
- package.json
- yarn.lock
<details>
<br/>
- Includes updated `/docs/demo-bundle.js` if source or docs code was changed.
- EXCEPTION: A Changeset is not required if the change does not affect any of the source files that produce the package bundle. For example, tooling changes, test updates, or a new dev-only dependency to run tests more efficiently should not have a Changeset since it …
> Bump tabbable to 5.2.1

- .changeset/cool-pans-obey.md
- docs/demo-bundle.js
- index.js
Fixes #498
<details>
<br/>
- EXCEPTION: A Changeset is not required if the change does not affect any of the source files that produce the package bundle. For example, tooling …
> Pass KeyboardEvent to escapeDeactivates option when it's a function

- .changeset/small-bugs-jam.md
- package.json
- yarn.lock
<details>
<br/>
- ⚠️ Non-covered demos (look for `IS_CYPRESS_ENV === ''` [here](https://github.com/focus-trap/focus-trap/blob/master/docs/js/index.js), as well as `in-open-shadow-dom.js` and `negative-tabindex.js` that can't be fully tested in Cypress) __manually__ verified.
- Careful to test `typeof …
> Bump tabbable to v5.3.2

- .changeset/fast-pianos-explode.md
- package.json
- yarn.lock
<details>
<br/>
- Careful to test `typeof document/window !== 'undefined'` before using it in code …
> Bump tabbable to v6.0.1 for bug fix

- .github/workflows/ci.yml
<details>
<br/>
- Careful to test `typeof document/window !== 'undefined'` before using it in code …
> Upgrade CI cypress image

- .changeset/pretty-fishes-happen.md
- package.json
- yarn.lock
<details>
<br/>
- Careful to test `typeof document/window !== 'undefined'` before using it in code …
> Bump tabbable to v6.1.1

- .github/workflows/ci.yml
- .github/workflows/release.yml
<details>
<br/>
- Careful to test `typeof document/window !== 'undefined'` before using it in …
> Disable cache for now

- .changeset/hungry-wolves-do.md
- package-lock.json
- package.json
<details>
<br/>
- Careful to test `typeof document/window !== 'undefined'` before using it in …
> Bump tabbable to v6.1.2 for nwsapi patch

- index.js
This PR is meant to fix a couple of bugs in https://github.com/focus-trap/focus-trap/pull/974 and, at the same time, simplify some logic around the fixes.
<details>
<br/>
- ⚠️ Non-covered demos (look for `// TEST MANUALLY` comments [here](https://github.com/focus-trap/focus-trap/blob/master/docs/js/index.js)) that can't be fully tested in Cypress have been …
> Positive tabindex

- .github/pull_request_template.md
- docs/js/index.js
After #996, try to remember to check Safari... 😓 
<details>
<br/>
- Careful to test `typeof …
> Web API browser compatibility checklist

- .all-contributorsrc
- .changeset/old-cows-sneeze.md
- README.md
- index.js
- Replaced `findIndex` with native implementation
- I had issues running tests, localy, it spawned with commands not found
<details>
<br/>
- Web APIs introduced have __deep__ browser coverage, including Safari (often very late to adopt new APIs).
- ⚠️ Non-covered demos (look for `// TEST MANUALLY` comments [here](https://github.com/focus-trap/focus-trap/blob/master/docs/js/index.js)) that can't be fully tested in Cypress have been __manually__ …
> fix: replace findIndex with native implementation
