index.js
I was seeing this happen on IE11 on various versions of Windows.
=> Fix crash on IE11 when previouslyFocused is null

index.js
This change fixes the functionality which detects pointer events
outside of the focus trap.
Before, ANY pointer event, even inside of the focus trap, deactivated
it. By using the containers contain function with the events target,
this problem was fixed.
=> Fix Outside Detection

index.js
Problem that this pull is solving.
1) You have one trap that is paused, not deactivated, and then you have another which is listening.
2) When you call deactivate (or pause) on first one, it passes current condition (since it is still active, even though it is paused, and there is listeningFocusTrap) and set listeningFocusTrap to null.
3) When you then call deactivate (or pause) on the second trap (which is listening), it doesn't pass condition, because, even though it is really listening, listeningFocusTrap was set to null in step 2. So you end up in situation where you can't remove listeners of this trap.
Problem lies in condition that allows paused trap to set listeningFocusTrap to null.
=> fix condition in removeListeners

README.md, demo/index.html, demo/js/demo-seven.js, demo/js/index.js, index.js
Added fallbackFocus option as proposed in #18.
Left description in README empty so that you can propose what to write there.
(Also fixed unneeded space before `returnFocusOnDeactivate` option)
=> Add fallbackFocus option

demo/index.html, demo/js/demo-eight.js, demo/js/index.js, index.js
I have a focus trap for an input that is automatically activated when the user types something in that input.
During the activation the library is not checking if the node to focus is the same already focused, resulting in a misleading behavior: while user is inputing characters, the text become selected and continuing typing overwrites previously inserted chars. 
This PR just do this check in tryFocus() before focusing:
`
if (node === document.activeElement)  return;
`
=> Don't (re)focus and select if focus is already in the target element during trap activation

README.md, index.d.ts
The README didn't reflect the options parameter it can receive, and the TypeScript definitions file had it as required when in reality it's optional.
=> Improve activate method signature in readme and TypeScript definitions

package-lock.json, package.json
This change allows `focus-trap` to be used in React components rendered on server side.
See [tabbable PR#33](https://github.com/davidtheclark/tabbable/pull/33)
=> Upgrade the version of tabbable to 3.1.1

CHANGELOG.md, README.md, demo/index.html, demo/js/allowoutsideclick.js, demo/js/index.js, index.d.ts, index.js
Solves problems like https://github.com/davidtheclark/focus-trap/issues/87 .
Might also solve problems like https://github.com/davidtheclark/focus-trap/pull/70#issuecomment-481014584, if you want to prevent all the clicks but the clicks on a specific element, that is for example responsible for activating/deactivating the focus trap (i.e. a button that opens a dropdown).
Demo video: https://www.dropbox.com/s/ryso8l3u5s14c23/focus-trap-allowoutsideclick-demo.mov?dl=0
=> Add `allowOutsideClick` option

README.md, demo/index.html, demo/js/index.js, demo/js/set-return-focus.js, index.d.ts, index.js
This option is useful when it is needed to set the returning element after deactivation programmatically.
In my case, another 3rd party library for modals sets the focus on the modal container. As I'm using the focus trap on modal, then the modal container focusing is called before focus trap sets the `state.nodeFocusedBeforeActivation`, which means after closing the modal focus trap won't return to previously focused element.
With this option I can manually set where it should return.
=> Add setReturnFocus after deactivation option

index.js
As noted in [this issue](https://github.com/davidtheclark/focus-trap/issues/104), I've been encountering a bug in IE where element focus causes the screen to scroll.
Per [MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/focus), there is an optional parameter you can pass in that defaults to `{preventScroll: false}`.
I propose we add the ability to pass down `preventScroll` from userOptions in order to grant flexibility for whether or not devs want the focus to trigger page scroll. On line 309, I added `{preventScroll: userOptions.preventScroll}`.
=> feat: Add option for preventing scroll

CHANGELOG.md, README.md, demo/index.html, demo/js/allowoutsideclick.js, index.d.ts, index.js
This adds support for boolean value to be passed to the `allowOutsideClick` option. This addresses focus-trap/focus-trap-react#86 and is the follow-up to focus-trap/focus-trap-react#87.
When describing the type of `allowOutsideClick`, I went with "If set and is or returns `true`". There may be a better wording for this.
I wanted to add an example without cluttering the page with another example that is visually identical. I opted for a `select` element to switch between passing a function or a boolean. This is contained in ceec9da.
=> feat: Add boolean value support for allowOutsideClick option

index.d.ts
[Recent PR](https://github.com/focus-trap/focus-trap/pull/120) contains invalid syntax for new option, this fixes.
=> ts: fix TypeScript syntax for allowOutsideClick option

.github/workflows/ci.yml, README.md, cypress.json, cypress/fixtures/example.json, cypress/integration/focus-trap-demo.spec.js, cypress/plugins/index.js, cypress/support/index.js, demo/index.html, package.json, yarn.lock
Since 'the demo is also the test' in this repo, let's use the
advent of Cypress (which is able to effectively test things
related to focus, unlike unit tests with JSDom, which doesn't
fully support focus events) to automate running all the demos
and exercise the focus-trap API.
NOTE: `demo/index.html` is UNCHANGED in functionality. I just
added a wrapper div with ID to each demo to make it easier
to find each demo when running Cypress tests.
The framework is in place, and the first demo is tested. Other
demos are TODO. I'm hoping to get community help to complete them.
See #143
=> Add Cypress e2e tests against the demos

.changeset/fuzzy-walls-kiss.md, package.json
This will cause the script (i.e. the build) to run:
1. when you run `yarn install` in the project after cloning the repo;
2. before publishing;
3. when installing the package from its git repo (an undocumented feature),
which is convenient if someone forks the repo to fix a bug and installs the
package from their fork until the bug fix is merged and a new package
version published.
Thanks to https://github.com/focus-trap/tabbable/pull/60 for pointing this out!
=> prepublishOnly -> prepare

.changeset/wise-terms-heal.md, .eslintignore, README.md, cypress/integration/focus-trap-demo.spec.js, demo/index.html, demo/js/index.js, demo/js/no-delay.js, index.d.ts, index.js
A change was introduce to add delay before autofocus in this PR https://github.com/focus-trap/focus-trap/pull/51 . The example given was https://codepen.io/anon/pen/RyvdEZ?editors=1111. Looking at the example, the bug described in the issue is not a `focus-trap` bug. 
The desired effect @pgn-vole was hopping to achieve could be done by calling `e.preventDefault()` on the event handler on the example instead of using `setTimeout`.
This change has not allowed us to upgrade to the latest version `6.0.1` because the behaviour of `createFocusTrap` changed without any additional documentation.
We are using this awesome library in the [atom text editor](https://github.com/atom/atom/pull/21256) 
~- [] Test coverage added/updated.~
~- [ ] Typings added/updated.~
~- [ ] README updated (API changes, …
=> Add delayInitialFocus option

.changeset/loud-countries-sit.md, cypress/integration/focus-trap-demo.spec.js, demo/index.html, demo/js/click-outside-deactivates.js, index.js
Fixes #103
The flag wasn't being respected when the trap is deactivated as
a result of `clickOutsideDeactivates=true` option.
=> Respect returnFocusOnDeactivate when deactivating trap

.changeset/stale-carpets-decide.md, package.json, yarn.lock
That version of tabbable has transpiled non-minified bundles, which
will help with #172.
=> Bump tabbable dependency to 5.1.1

README.md
It looks like that with the transition to a Github org, the demo link was missed in the readme. Lemme know if I messed up the formatting in this PR.
=> Update demo link in readme

.changeset/dull-wolves-change.md, package.json, yarn.lock
To help close the gap with #172, bump the version since it has a
similar fix to tabbable.
=> Bump tabbable to 5.1.2

.changeset/tidy-suns-notice.md, README.md, cypress/integration/focus-trap-demo.spec.js, demo/index.html, demo/js/index.js, demo/js/multiple-elements.js, demo/js/multiple-traps-multiple-elements.js, demo/js/sibling.js, demo/style.css, index.d.ts, index.js
Add support for passing in multiple elements
Note that only passing in a single element is still supported
-------------------
Demo 1
Demo 2
=> Add support for passing in multiple elements

.changeset/slimy-ducks-whisper.md, README.md, cypress/integration/focus-trap-demo.spec.js, demo/index.html, demo/js/index.js, demo/js/multiple-elements-delete-all.js, demo/js/multiple-elements-delete.js, index.js
Fixes #223 and adds an exception thrown if the trap is allowed to get into a state where none of its containers contain any tabbable nodes (there must always be at least one container that has at least one tabbable node among all containers configured) -- unless the `fallbackFocus` option has been configured to provide a fallback node.
=> Allow trap containers to have no tabbable nodes

.changeset/eight-stingrays-hunt.md, index.js
=> Use a small alternative to Array.findIndex() not supported on IE

cypress/integration/focus-trap-demo.spec.js, demo/iframe-content.html, demo/index.html
I've made several accessibility improvements to the demo site for semantic HTML correctness and also to help screen reader users. I've tested my fixes using the VoiceOver screen reader on a Mac and also with the axe Chrome extension.
The fixes include:
- wrap all page content in a `main` element
- add an `aria-hidden="true"` attribute to the pointing finger icon so screen readers ignore it
- add contextual labels on the "activate trap" and "deactivate trap" buttons
- fix the closing tag on the iframe HTML document to be a div and not an anchor tag, and then change the `div` to a `main`
- update the Cypress tests to still pass with the new changes
These changes are very similar to the changes I made over in the `focus-trap-react` repo in this PR: …
=> docs: adds a11y improvements to the demo

.changeset/old-bottles-notice.md, cypress/integration/focus-trap-demo.spec.js, index.js
Fixes #281
<details>
<br/>
- EXCEPTION: A Changeset is not required if the change does not affect any of the source files that produce the package bundle. For example, tooling changes, test updates, or a new dev-only dependency to run tests more efficiently should not have a Changeset since it will not affect package consumers.
</details>
=> Fix focus escape when press TAB after hiding element with focus

.github/workflows/ci.yml, package.json, yarn.lock
This is a browser library. There's no need to test on two versions
of Node. It's not meant to run on Node anyway. We just use Node
to run JSDom for unit tests.
<details>
<br/>
- EXCEPTION: A Changeset is not required if the change does not affect any of the source files that produce the package bundle. For example, tooling changes, test updates, or a new …
=> Upgrade to Cypress 7.1.0 and drop testing on Node 12

.changeset/stupid-snakes-complain.md, cypress/integration/focus-trap-demo.spec.js, index.js
Fixes #363
<details>
<br/>
- EXCEPTION: A Changeset is not required if the change does not affect any of the source files that produce the package bundle. For example, tooling changes, test updates, or a new dev-only dependency to run tests more efficiently should not have a Changeset since it will not affect package consumers.
</details>
=> Fix focus stuck on tabindex=-1 container with shift+tab

.github/workflows/ci.yml, cypress/integration/focus-trap-demo.spec.js
Toward #143
<details>
<br/>
- EXCEPTION: A Changeset is not required if the change does not affect any of the source files that produce the package bundle. For example, tooling changes, test updates, or a new dev-only dependency to run tests more efficiently should not have a Changeset since it will not affect package consumers.
</details>
=> Add Firefox to Cypress matrix

.changeset/warm-pugs-jump.md, README.md, index.d.ts
No reason why "DOM node" can't be an SVGElement too, since those are focusable and therefore can be tabbable.
<details>
<br/>
- EXCEPTION: A Changeset is not required if the change does not affect any of the source files that produce the package bundle. For example, tooling changes, test updates, or a new dev-only dependency to run tests more efficiently …
=> Improve docs and types for most options

.changeset/little-melons-remember.md, docs/demo-bundle.js, index.js
Fixes #441
Activating of the second trap, causing the first trap to pause and
remove listeners may sometimes thwart delayed initial focus in second
trap.
<details>
<br/>
- Includes updated `/docs/demo-bundle.js` if source or docs code was changed.
- EXCEPTION: A Changeset is not required if the change does not affect any of the source files that produce the …
=> [#441] Fix race delayed initial focus race condition

.changeset/breezy-oranges-play.md, README.md, index.js
This option shouldn't be called _unless_ there's a mouse/touch click
_outside_ the trap. Yet it was being called regardless on the 'click'
event.
<details>
<br/>
- ⚠️ Non-covered demos (look for `IS_CYPRESS_ENV === ''` [here](https://github.com/focus-trap/focus-trap/blob/master/docs/js/index.js), as well as `in-open-shadow-dom.js` and `negative-tabindex.js` that …
=> Fix when clickOutsideDeactivates gets called on click

.changeset/hip-zoos-bathe.md, README.md
Fixes #783
<details>
<br/>
- Careful to test `typeof document/window !== 'undefined'` before using …
=> [783] Add mention about Safari tab setting in README

CONTRIBUTING.md
While working on another issue I stumbled on a few inconsistencies in `CONTRIBUTING.md`. This involves working with Cypress tests and changesets. This PR tries to fix these.
There is no longer a script name called `test:cypress`. The correct script name for running Cypress tests in interactive mode is `test:e2e:dev`.
The documentation currently refers to running `npm run changeset` but there is no `changeset` script in `package.json`.
Using `npx` to run the executable from `changeset/cli` seems to be the best bet.
One alternative approach would be to add a `changeset` script to execute `changeset/cli`.
<details>
<br/>
- Includes updated docs demo bundle if …
=> Update contributor documentation

.changeset/afraid-carrots-lick.md, index.js
This PR removes all the references to `Array.prototype.findLast()` in the codebase, because it doesn't have acceptable [browser support](https://caniuse.com/mdn-javascript_builtins_array_findlast).
Fixes https://github.com/focus-trap/focus-trap/issues/996.
<details>
<br/>
- ⚠️ Non-covered demos (look for `// TEST MANUALLY` comments …
=> Remove references to `Array.prototype.findLast()`

.changeset/thirty-baboons-push.md, eslint.config.mjs, package-lock.json, package.json
Fixes #1343
<details>
<br/>
- Web APIs introduced have __deep__ browser coverage, including Safari (often very late to adopt new APIs).
- Typings …
=> Remove recently-added engine requirement
